"""集中管理所有 LLM prompt，便于版本化和 A/B 测试。

每个 prompt 包含：版本号、system 部分、可选的 few-shot 示例。
在代码里通过 from app.prompts import xxx 引用，不要再 inline 写 prompt。
"""

from app.prompts.agent_system import AGENT_SYSTEM_PROMPT, AGENT_SYSTEM_VERSION
from app.prompts.compound import (
    COMPOUND_SYNTH_SYSTEM,
    COMPOUND_SYNTH_USER,
    COMPOUND_SYNTH_VERSION,
)
from app.prompts.decompose import DECOMPOSE_SYSTEM, DECOMPOSE_USER, DECOMPOSE_VERSION
from app.prompts.identify import IDENTIFY_FROM_URL_TEMPLATE, IDENTIFY_VERSION
from app.prompts.intent import INTENT_CLASSIFIER_SYSTEM, INTENT_CLASSIFIER_VERSION
from app.prompts.playlist import (
    AUTO_PLAYLIST_TEMPLATE,
    GENERATE_PLAYLIST_TEMPLATE,
    PLAYLIST_VERSION,
)
from app.prompts.query_plan import (
    QUERY_PLAN_REPAIR_SYSTEM,
    QUERY_PLAN_REPAIR_USER,
    QUERY_PLAN_SYSTEM,
    QUERY_PLAN_VERSION,
)
from app.prompts.recommend import (
    DAILY_RECOMMEND_USER_TEMPLATE,
    DAILY_RECOMMEND_VERSION,
    DAILY_SUMMARY_TEMPLATE,
)
from app.prompts.reflect import REFLECTION_SYSTEM, REFLECTION_VERSION
from app.prompts.search import LLM_SEARCH_TEMPLATE, LLM_SEARCH_VERSION

__all__ = [
    "AGENT_SYSTEM_PROMPT",
    "AGENT_SYSTEM_VERSION",
    "COMPOUND_SYNTH_SYSTEM",
    "COMPOUND_SYNTH_USER",
    "COMPOUND_SYNTH_VERSION",
    "DECOMPOSE_SYSTEM",
    "DECOMPOSE_USER",
    "DECOMPOSE_VERSION",
    "INTENT_CLASSIFIER_SYSTEM",
    "INTENT_CLASSIFIER_VERSION",
    "REFLECTION_SYSTEM",
    "REFLECTION_VERSION",
    "DAILY_RECOMMEND_USER_TEMPLATE",
    "DAILY_RECOMMEND_VERSION",
    "DAILY_SUMMARY_TEMPLATE",
    "LLM_SEARCH_TEMPLATE",
    "LLM_SEARCH_VERSION",
    "GENERATE_PLAYLIST_TEMPLATE",
    "AUTO_PLAYLIST_TEMPLATE",
    "PLAYLIST_VERSION",
    "IDENTIFY_FROM_URL_TEMPLATE",
    "IDENTIFY_VERSION",
    "QUERY_PLAN_REPAIR_SYSTEM",
    "QUERY_PLAN_REPAIR_USER",
    "QUERY_PLAN_SYSTEM",
    "QUERY_PLAN_VERSION",
]
